# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(360, 312)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnChooseFile = QtWidgets.QPushButton(self.centralwidget)
        self.btnChooseFile.setGeometry(QtCore.QRect(70, 30, 231, 23))
        self.btnChooseFile.setObjectName("btnChooseFile")
        self.url = QtWidgets.QLineEdit(self.centralwidget)
        self.url.setGeometry(QtCore.QRect(70, 70, 231, 20))
        self.url.setObjectName("url")
        self.apikey = QtWidgets.QLineEdit(self.centralwidget)
        self.apikey.setGeometry(QtCore.QRect(70, 100, 231, 20))
        self.apikey.setObjectName("apikey")
        self.code = QtWidgets.QComboBox(self.centralwidget)
        self.code.setGeometry(QtCore.QRect(70, 130, 231, 22))
        self.code.setObjectName("code")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 160, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.delay = QtWidgets.QSpinBox(self.centralwidget)
        self.delay.setGeometry(QtCore.QRect(140, 160, 42, 22))
        self.delay.setMinimum(1)
        self.delay.setObjectName("delay")
        self.btnEvent = QtWidgets.QPushButton(self.centralwidget)
        self.btnEvent.setGeometry(QtCore.QRect(140, 230, 101, 31))
        self.btnEvent.setObjectName("btnEvent")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 190, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.getprefix = QtWidgets.QSpinBox(self.centralwidget)
        self.getprefix.setGeometry(QtCore.QRect(140, 190, 42, 22))
        self.getprefix.setMinimum(1)
        self.getprefix.setObjectName("getprefix")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 360, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AUTO UP ACCOUNT FOR SHOPCLONE V7"))
        self.btnChooseFile.setText(_translate("MainWindow", "Chọn FIle"))
        self.url.setText(_translate("MainWindow", "https://zshopclone7.cmsnt.net"))
        self.apikey.setText(_translate("MainWindow", "APIKEY"))
        self.label.setText(_translate("MainWindow", "Delay"))
        self.btnEvent.setText(_translate("MainWindow", "CHẠY"))
        self.label_2.setText(_translate("MainWindow", "Lấy |"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
